server:
    port: 9000
    contextPath:

spring:
    profiles:
        active: dev
    freemarker: 
        cache: false

    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/yiding?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 741369

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: create
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400
    

